name: Contract verification

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      contract_address:
        description: "Smart contract address to verify"
        required: true
      source_code_path:
        description: "Path to the source code file"
        required: true
      contract_name:
        description: "Name of the contract to verify"
        required: true
      chain:
        description: "Blockchain network (e.g., mainnet, avalanche, plasma)"
        required: false
        default: "mainnet"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bgd-labs/github-workflows/.github/actions/setup-node@main

      - name: Enforce linting
        run: npm run lint --check

  test-sol:
    name: Foundry contract verification
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: bgd-labs/action-rpc-env@main
        with:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      # we simply use foundry zk for all jobs in this repo
      - name: Run Foundry setup
        uses: bgd-labs/github-workflows/.github/actions/foundry-setup@main
        with:
          ZKSYNC: "true"

      - name: Verify contract

        run: forge verify-contract ${{ inputs.contract_address }} ${{ inputs.source_code_path }}:${{ inputs.contract_name }} --chain ${{ inputs.chain }} --watch
